version: '3'

tasks:
  clean:
    cmds:
      - cargo clean
      - rm -rf lancemate/node_modules
  fmt:
    cmds:
      - cargo fmt
      - find mesc/c_src/MESC_Common/ -iname '*.h' -o -iname '*.c' -o -iname '*.cpp'| xargs clang-format -i
      - find mesc/c_src/hardware_conf/ -iname '*.h' -o -iname '*.c' -o -iname '*.cpp'| xargs clang-format -i

  all_targets: task --list-all | grep --color=never build
  begode_etmax:
    internal: true
    vars:
      CARGO_METHOD: '{{.CARGO_METHOD}}'
    cmds:
      - |
        TARGET_PORT=stm32 TARGET_NAME=begode_etmax \
        cargo {{.CARGO_METHOD}} -p port-stm32 \
          --no-default-features --features board_begode_etmax \
          --target thumbv7em-none-eabihf {{.CLI_ARGS}}

  begode_etmax:build:
    cmds:
      - task: begode_etmax
        vars:
          CARGO_METHOD: build
  begode_etmax:fix:
    cmds:
      - task: begode_etmax
        vars:
          CARGO_METHOD: fix
  begode_etmax:expand:
    cmds:
      - task: begode_etmax
        vars:
          CARGO_METHOD: expand
  begode_etmax:clippy:
    cmds:
      - task: begode_etmax
        vars:
          CARGO_METHOD: clippy
  begode_etmax:bloat:
    cmds:
      - task: begode_etmax
        vars:
          CARGO_METHOD: bloat
