version: '3'

# TODO: Rewrite all of this with either a custom build tool or with a Justfile.
tasks:
  clean:
    cmds:
      - cargo clean
      - rm -rf lancemate/node_modules
  fmt:
    cmds:
      - cargo +nightly fmt
      - find mesc/c_src/MESC_Common/ -iname '*.h' -o -iname '*.c' -o -iname '*.cpp'| xargs clang-format -i

  all_targets:list: task --list-all | grep --color=never build
  all_targets:build:
    cmds:
      - task: naegi:build

  naegi:
    internal: true
    vars:
      CARGO_METHOD: '{{.CARGO_METHOD}}'
    cmds:
      - |
        cargo {{.CARGO_METHOD}} -p port-stm32 \
          --no-default-features --features board_naegi \
          --target thumbv7em-none-eabihf {{.CLI_ARGS}}

  naegi:build:
    cmds:
      - task: naegi
        vars:
          CARGO_METHOD: build
  naegi:fix:
    cmds:
      - task: naegi
        vars:
          CARGO_METHOD: fix
  naegi:expand:
    cmds:
      - task: naegi
        vars:
          CARGO_METHOD: expand
  naegi:clippy:
    cmds:
      - task: naegi
        vars:
          CARGO_METHOD: clippy
  naegi:bloat:
    cmds:
      - task: naegi
        vars:
          CARGO_METHOD: bloat
  control:doc:
    cmds:
      - cargo doc -p core-control {{.CLI_ARGS}}

  supervisor:doc:
    cmds:
      - cargo doc -p core-supervisor {{.CLI_ARGS}}
