# NOTE: This file is only here so that my LSP works properly. To actually build the firmware,
# use for example `task naegi:build`. For all supported targets, do `task --list-all`.

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
