# NOTE: This file is only here so that my LSP works properly. To actually build the firmware,
# use for example `task build-bg-etmax`. For all supported targets, do `task --list-all`.

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F405RG"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
