name: Build all targets

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Task
        run: curl -1sLf 'https://dl.cloudsmith.io/public/task/task/setup.deb.sh' | sudo -E bash && sudo apt install task
      - name: Install arm-none-eabi-gcc
        run: curl -O https://developer.arm.com/-/media/Files/downloads/gnu/15.2.rel1/binrel/arm-gnu-toolchain-15.2.rel1-x86_64-arm-none-eabi.tar.xz \
          && sudo tar xjf arm-gnu-toolchain-15.2.rel1-x86_64-arm-none-eabi.tar.xz -C /usr/share/ \
          && sudo ln -s /usr/share/arm-gnu-toolchain-15.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc /usr/bin/arm-none-eabi-gcc \
          && sudo ln -s /usr/share/arm-gnu-toolchain-15.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-g++ /usr/bin/arm-none-eabi-g++ \
          && sudo ln -s /usr/share/arm-gnu-toolchain-15.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gdb /usr/bin/arm-none-eabi-gdb \
          && sudo ln -s /usr/share/arm-gnu-toolchain-15.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-size /usr/bin/arm-none-eabi-size \
          && sudo ln -s /usr/share/arm-gnu-toolchain-15.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-objcopy /usr/bin/arm-none-eabi-objcopy \
      - name: Verify arm-none-eabi-gcc version
        run: arm-none-eabi-gcc --version \ 
          && arm-none-eabi-g++ --version \ 
          && arm-none-eabi-gdb --version \
          && arm-none-eabi-size --version \
      - uses: actions/checkout@v4
      - name: Build
        run: task all_targets:build
        # TODO: when there will be any tests, make sure that they are executed here

