name: Build all targets

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Task
        run: curl -1sLf 'https://dl.cloudsmith.io/public/task/task/setup.deb.sh' | sudo -E bash && sudo apt install task

      - uses: actions/checkout@v4
      - name: Install arm-none-eabi-gcc
        run: chmod +x ./.github/arm_none_eabi_ubuntu_install.sh && ./.github/arm_none_eabi_ubuntu_install.sh

      - name: Verify arm-none-eabi-gcc version
        run: arm-none-eabi-gcc --version \ 
          && arm-none-eabi-g++ --version \ 
          && arm-none-eabi-gdb --version \
          && arm-none-eabi-size --version \

      - name: Configure Rust
        run: rustup default nightly && rustup target add thumbv7em-none-eabihf

      - name: Build
        run: task all_targets:build -- --release
        # TODO: when there will be any tests, make sure that they are executed here
        # TODO: make it also upload all built binaries
        # For that I will most likely need a modification to the task runner commands so
        # it automatically extracts any build artifacts and stores them
